### ISSUE TITLE
Article text should be white

### ISSUE THREAD

**Issue by InterstellarOne** [InterstellarOne/Tidal-Light#14]
Articles on Artist pages should be white, or contrast better in some other way. 
https://listen.tidal.com/artist/6743691

![Image](https://github.com/user-attachments/assets/4a182fc1-448f-46ee-9830-8f534c4360d0)

**Comment by rattmuffen** [comment]
White text with black border might work for most backgrounds?
```css
._titleText_5488c61 {
  color: white !important;
  -webkit-text-stroke: black 1px;
}
```
seems to have good browser compatibility
https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke#browser_compatibility
