### ISSUE TITLE
Explicit badge bg is white

### ISSUE THREAD

**Issue by InterstellarOne** [InterstellarOne/Tidal-Light#18]
It should be grey (can be colour picked by the preview image)

**Comment by rattmuffen** [comment]
It's a bit tricky since its the color of a SVG, but its possible with the CSS filter function to alter it:
```css
    ._explicitBadge_b93510b {
        filter: invert(100%) sepia(0%) saturate(100%) hue-rotate(100deg) brightness(130%) contrast(85%);
    }
```

looks like this:
![Image](https://github.com/user-attachments/assets/4f0b7d5c-9588-4d84-820d-2de24cd531a7)
