### ISSUE TITLE
Remove black gradient on Now Playing menu

### ISSUE THREAD

**Issue by InterstellarOne** [InterstellarOne/Tidal-Light#3]
I can't find a target selector

**Comment by rattmuffen** [comment]
Is it this gradient above the player controls you mean:

![Image](https://github.com/user-attachments/assets/82ff1370-042f-4081-b222-1ae1ae7aa0fa)

Then I might have found a selector:
```css
._bottomGradient_5c344de {
  background: none !important;
}
```


after:

![Image](https://github.com/user-attachments/assets/961e9bb3-97c1-4b86-85a7-07676035ad24)
