### ISSUE TITLE
Audio quality header gradient too dark

### ISSUE THREAD

**Issue by rattmuffen** [InterstellarOne/Tidal-Light#33]
![Image](https://github.com/user-attachments/assets/97824219-3bd7-42f9-ad79-79a0fd514660)

**Comment by rattmuffen** [comment]
Suggestion: set `background-color` to transparent on the element:
```css
    ._containerMax_611862e {
        background-color: transparent !important;
    }
```
looks like this:

![Image](https://github.com/user-attachments/assets/a3ae5692-fb3c-4705-b687-84b488f58ed6)

the element class name is generic though... maybe affects other places?
